language: cpp

compiler:
  - g++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -yqq g++-4.8 gcc-4.8 valgrind
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"

script: mkdir build && cd build && cmake .. && make && ./test/test-driver &&
    valgrind --error-exitcode=1 ./test/test-driver
